const batterConsistency = "smooth";
console.log(batterConsistency);
const patelniaTemperature = 210;
console.log(patelniaTemperature);
const cookingTime = 10;
console.log(cookingTime);
const flipCount = 4;
console.log(flipCount);
const ingredientList = ["apple", "blueberry", "chocolate", "grape", "pear"];
console.log(ingredientList);
const batterVolume = "dense";
console.log(batterConsistency);
const servingSize = "medium";
console.log(servingSize);
const toppingChoice = ["chocolate", "cream", "custard"];
console.log(toppingChoice);
let remainingBatter = 2.5;
console.log(remainingBatter);
const patelniaOilLevel = 0.3;
console.log(patelniaOilLevel);
