let batterConsistency = 'рідке тісто';
let patelniaTemperature = 200;
let cookingTime = '2 хвилини';
let flipCount = 2;
let ingredientList = 'молоко, мука, цукор, яйця';
let batterVolume = '1.5 літри';
let servingSize = '50 грамів';
let toppingChoice = 'курчак або сир';
let remainingBatter = '30 грамів';
let patelniaOilLevel = 10;
console.log(batterConsistency);
console.log(patelniaTemperature);
console.log(cookingTime);
console.log(flipCount);
console.log(ingredientList);
console.log(batterVolume);
console.log(servingSize);
console.log(toppingChoice);
console.log(remainingBatter);
console.log(patelniaOilLevel);